#!/usr/bin/env bash

PS1='[\u@\h \W]\$ '

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#############################
#Customization
#############################

eval "$(starship init bash)"

alias discord="$HOME/sharing/stuffs/softwares/linux/appimages/Discord-latest-x86_64.AppImage"

#export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.local/bin/"
#export PATH="$PATH:$HOME/.local/bin/"
#export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.local/bin/:$HOME/.pyenv/bin"

export APPIMAGE="$HOME/sharing/stuffs/softwares/linux/appimages/"

export TCC="$HOME/sharing/projects_myself/trabalho_conclusao_curso/"
export VAL="$HOME/Downloads/val/val_python/"
#export VAL="$HOME/sharing/projects_myself/testing/"
export FONTS="$HOME/sharing/projects_myself/package_manager_typography/"

source ~/.local/bin/_aliasrc
#alias ls='ls --color=auto'
alias yyy="vim $HOME/.bashrc && source $HOME/.bashrc"
alias zzz="$EDITOR $HOME/.config/i3/config && i3-msg reload && i3-msg restart"

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#poetry env use ~/.pyenv/versions/3.6-dev/bin/python3.6
alias pip36="$HOME/.pyenv/versions/3.6-dev/bin/pip" #pip, pip3, pip3.6
alias python36="$HOME/.pyenv/versions/3.6-dev/bin/python3.6"

export TERM=alacritty

#alias asdf="$HOME/.asdf/asdf.sh"
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

#neofetch
